name: Project CI


on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write        # ✅ para subir a Pages
  id-token: write     # ✅ para autenticación OIDC

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@v3
      - run: uv sync --all-extras
      - run: uv pip install sphinx furo myst-parser
      - run: uv run sphinx-apidoc -o docs/api src/mkit --force
      - name: List docs directory
        run: |
          echo "📂 Contents of docs/"
          ls -R docs
      - run: uv run sphinx-build -b html docs docs/_build/html
      - uses: actions/upload-artifact@v4
        with:
          name: docs-preview
          path: docs/_build/html
  docs-deploy:
    runs-on: ubuntu-latest
    needs: docs
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/deploy-pages@v4

  
  call-devops-ci:
    needs: [docs]
    uses: ./.github/workflows/python-ci.yml
    with:
      python-version: "3.12"
      src-dir: "src"
      test-dir: "src/tests"
      coverage-threshold: "81"
      linter-fail-on: "any"
      security-fail-on: "medium"
    permissions:
      contents: read
      pull-requests: write
    secrets: 
      pypi-secret: ${{ secrets.TEST_PYPI_API_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      codecov-token: ${{ secrets.CODECOV_TOKEN }}


